import 'package:flutter/material.dart';

class AppConsts {
  static const List<(Locale, String)> languages = [
    (Locale('sq'), 'Albanian - Shqip'),
    (Locale('ar'), 'Arabic - عربي'),
    (Locale('az'), 'Azerbaijani - Azərbaycan'),
    (Locale('eu'), 'Basque - Euskara'),
    (Locale('bn'), 'Bengali - বাংলা'),
    (Locale('bg'), 'Bulgarian - Български'),
    (Locale('ca'), 'Catalan - Català'),
    (
      Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans'),
      'Chinese (Simplified) - 中文',
    ),
    (
      Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'),
      'Chinese (Traditional) - 繁體中文',
    ),
    (Locale('hr'), 'Croatian - Hrvatski'),
    (Locale('cs'), 'Czech - Čeština'),
    (Locale('da'), 'Danish - Dansk'),
    (Locale('nl'), 'Dutch - Nederlands'),
    (Locale('en'), 'English'),
    (Locale('eo'), 'Esperanto - Esperanto'),
    (Locale('et'), 'Estonian - Eesti'),
    (Locale('fi'), 'Finnish - Suomi'),
    (Locale('fr'), 'French - Français'),
    (Locale('gl'), 'Galician - Galego'),
    (Locale('de'), 'German - Deutsch'),
    (Locale('el'), 'Greek - Ελληνικά'),
    (Locale('he'), 'Hebrew - עברית'),
    (Locale('hi'), 'Hindi - हिन्दी'),
    (Locale('hu'), 'Hungarian - Magyar'),
    (Locale('is'), 'Icelandic - Íslenska'),
    (Locale('id'), 'Indonesian - Bahasa Indonesia'),
    (Locale('ga'), 'Irish - Gaeilge'),
    (Locale('it'), 'Italian - Italiano'),
    (Locale('ja'), 'Japanese - 日本語'),
    (Locale('ko'), 'Korean - 한국어'),
    (Locale('lv'), 'Latvian - Latviešu'),
    (Locale('lt'), 'Lithuanian - Lietuvių'),
    (Locale('ms'), 'Malay - Bahasa Melayu'),
    (Locale('nb'), 'Norwegian - Norsk Bokmål'),
    (Locale('fa'), 'Persian - فارسی'),
    (Locale('pl'), 'Polish - Polski'),
    (Locale('pt'), 'Portuguese - Português'),
    (Locale('pt', 'BR'), 'Portuguese (Brazil) - Português (Brasil)'),
    (Locale('ro'), 'Romanian - Română'),
    (Locale('ru'), 'Russian - Русский'),
    (Locale('sk'), 'Slovak - Slovenčina'),
    (Locale('sl'), 'Slovenian - Slovenščina'),
    (Locale('es'), 'Spanish - Español'),
    (Locale('sv'), 'Swedish - Svenska'),
    (Locale('tl'), 'Tagalog - Tagalog'),
    (Locale('th'), 'Thai - ไทย'),
    (Locale('tr'), 'Turkish - Türkçe'),
    (Locale('uk'), 'Ukrainian - Українська'),
    (Locale('ur'), 'Urdu - اردو'),
    (Locale('zh'), 'Chinese'),
  ];

  static const String apiBaseUrl = String.fromEnvironment(
    'API_BASE_URL',
    defaultValue: 'http://127.0.0.1/qpi/',
  );
}
